"""Static authenticated browser UI for the loopback/central control hub."""

from __future__ import annotations


def render_control_ui() -> bytes:
    """Return a no-token-in-document UI; the token lives only in sessionStorage."""

    return r"""<!doctype html>
<html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Camera Agent Control</title>
<style>
:root{color-scheme:dark;--bg:#0b1020;--card:#17213a;--line:#2c3d63;--text:#edf3ff;--muted:#a7b4d0;--accent:#67e8f9;--ok:#55dca1;--bad:#fb7185}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:15px/1.4 system-ui,sans-serif}.shell{max-width:1100px;margin:auto;padding:24px}.grid{display:grid;grid-template-columns:1.5fr 1fr;gap:16px}.card{background:var(--card);border:1px solid var(--line);border-radius:16px;padding:18px}.preview{min-height:360px;display:grid;place-items:center;background:#060911;border-radius:12px;overflow:hidden}.preview img{max-width:100%;max-height:65vh;object-fit:contain}.field{display:grid;gap:5px;margin:10px 0}.field label,.muted{color:var(--muted);font-size:13px}select,input,button{font:inherit;border-radius:9px;padding:10px;border:1px solid var(--line);background:#0b1224;color:var(--text)}button{cursor:pointer;background:#1c3055;font-weight:650}button.primary{background:#14566e;border-color:#2ca7bb}button.danger{background:#5d1e36;border-color:#bf4b6d}.actions,.pad{display:grid;gap:8px}.actions{grid-template-columns:repeat(3,1fr);margin-top:14px}.pad{grid-template-columns:repeat(3,1fr);max-width:320px;margin:18px auto}.empty{visibility:hidden}.status{min-height:42px;white-space:pre-wrap;color:var(--muted)}dialog{border:1px solid var(--line);border-radius:16px;background:var(--card);color:var(--text);max-width:390px}.login{display:grid;gap:12px;min-width:300px}@media(max-width:800px){.shell{padding:14px}.grid{grid-template-columns:1fr}.preview{min-height:230px}}
</style></head><body><main class="shell">
<header><p class="muted">CAMERA AGENT · MAINFLUX CONTROL</p><h1>Điều khiển thiết bị</h1><p class="muted">Token chỉ tồn tại trong tab hiện tại. Mainflux không nhận token hay pixel camera.</p></header>
<div class="grid"><section class="card"><h2 id="cameraTitle">Camera</h2><div class="preview"><img id="preview" alt="Latest camera frame" hidden><p id="placeholder" class="muted">Đang chờ preview được opt-in từ agent.</p></div><p id="deviceState" class="muted">Đang tải danh sách thiết bị…</p></section>
<section class="card"><h2>Chọn & điều khiển</h2><div class="field"><label for="device">Thiết bị</label><select id="device"></select></div><div class="field"><label for="feature">Feature độc quyền</label><select id="feature"><option value="facebook_monitor">Facebook monitor</option><option value="person_guard">Person guard</option><option value="none">Không chạy feature</option></select></div><div class="actions"><button class="primary" id="apply">Áp dụng feature</button><button id="toggle">Bật/Tắt device</button><button class="danger" onclick="sendCommand('stop',{})">■ Stop</button></div><div class="actions"><button onclick="sendCommand('set_auto',{enabled:true})">Auto ON</button><button onclick="sendCommand('set_auto',{enabled:false})">Auto OFF</button><button class="danger" onclick="forget()">Đổi token</button></div><div class="pad"><span class="empty"></span><button onclick="move('up')">↑</button><span class="empty"></span><button onclick="move('left')">←</button><span class="empty"></span><button onclick="move('right')">→</button><span class="empty"></span><button onclick="move('down')">↓</button><span class="empty"></span></div><div id="status" class="status">Nhập token để bắt đầu.</div></section></div></main>
<dialog id="login"><form method="dialog" class="login"><h2>Nhập control token</h2><p class="muted">Token này điều khiển toàn bộ device được cấp quyền.</p><input id="tokenInput" type="password" autocomplete="current-password" required><button class="primary" value="ok">Mở control UI</button><p id="loginError" class="status"></p></form></dialog>
<script>
const $=id=>document.getElementById(id),tokenKey='camera-agent-control-token';let devices=[],current=null;
const token=()=>sessionStorage.getItem(tokenKey)||'',headers=()=>({'X-Control-Server-Token':token()});
function message(s,bad=false){$('status').textContent=s;$('status').style.color=bad?'var(--bad)':'var(--ok)'}
async function api(path,opts={}){let r=await fetch(path,{...opts,headers:{...headers(),...(opts.headers||{})}});let body=await r.json().catch(()=>({}));if(r.status===401){sessionStorage.removeItem(tokenKey);showLogin();throw Error('unauthorized')}if(!r.ok)throw Error(body.error||'Request failed');return body}
function showLogin(){let d=$('login');$('tokenInput').value='';$('loginError').textContent='';if(!d.open)d.showModal();$('tokenInput').focus()}
$('login').addEventListener('close',async()=>{let v=$('tokenInput').value;if(!v)return $('loginError').textContent='Cần nhập token.';sessionStorage.setItem(tokenKey,v);try{await loadDevices()}catch(e){$('loginError').textContent='Token hoặc control server không hợp lệ.';showLogin()}});
function forget(){sessionStorage.removeItem(tokenKey);showLogin()}
function selected(){return $('device').value}
function render(){let select=$('device');select.textContent='';for(let d of devices){let o=document.createElement('option');o.value=d.device_id;o.textContent=d.display_name+' · '+d.device_id;select.append(o)}if(current&&devices.some(d=>d.device_id===current))select.value=current;current=select.value;select.onchange=()=>{current=selected();renderState();refreshPreview()};renderState()}
function item(){return devices.find(d=>d.device_id===selected())}
function renderState(){let d=item();if(!d)return;$('cameraTitle').textContent=d.display_name;$('feature').value=d.desired_feature||d.default_feature||'facebook_monitor';for(let o of $('feature').options)o.disabled=o.value!=='none'&&!d.features.includes(o.value);$('toggle').textContent=d.runtime_enabled?'Standby device':'Bật device';$('deviceState').textContent=`Online: ${d.online?'YES':'NO'} · Feature: ${d.applied_feature||d.desired_feature||'-'} · Runtime: ${d.runtime_enabled?'ON':'STANDBY'} · ACK: ${d.applied_status||'pending'}`}
async function loadDevices(){let body=await api('/v1/devices');devices=body.devices||[];if(!devices.length)throw Error('No devices');current=current||devices[0].device_id;render();message('Sẵn sàng');refreshPreview()}
async function waitLocalCommand(commandId){for(let i=0;i<60;i++){await new Promise(r=>setTimeout(r,50));let c=await api('/v1/commands/'+encodeURIComponent(commandId));if(c.status==='executed')return {ok:true,detail:c.detail||''};if(['rejected','failed','expired'].includes(c.status))return {ok:false,detail:c.detail||c.status}}return {ok:false,detail:'agent did not acknowledge within 3 seconds'}}
async function desired(runtime,feature){try{let b=await api('/v1/devices/'+encodeURIComponent(selected())+'/desired-state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({runtime_enabled:runtime,feature})});if(b.status==='pending_local'&&b.command_id){message(`Applying ${feature} locally…`);let outcome=await waitLocalCommand(b.command_id);message(outcome.ok?`Applied: ${feature}. ${outcome.detail}`:`Feature was not applied: ${outcome.detail}`,!outcome.ok)}else{message(b.status==='sent'?`Desired state ${b.generation} sent via MQTT; waiting for ACK.`:`Desired state ${b.generation} saved; MQTT delivery is pending.`)}await loadDevices()}catch(e){message(e.message,true)}}
$('apply').onclick=()=>desired(item()?.runtime_enabled!==false,$('feature').value);$('toggle').onclick=()=>desired(!(item()?.runtime_enabled),item()?.desired_feature||$('feature').value);
async function sendCommand(action,payload){try{let b=await api('/v1/devices/'+encodeURIComponent(selected())+'/commands',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,payload})});if(b.status==='sent'){message('Lệnh đã gửi qua Mainflux; chờ agent ACK.')}else if(b.command_id){message('Đang áp dụng lệnh local…');let outcome=await waitLocalCommand(b.command_id);message(outcome.ok?`Đã áp dụng: ${outcome.detail}`:`Lệnh không thực hiện được: ${outcome.detail}`,!outcome.ok)}else{message('Lệnh đã xếp hàng.')}}catch(e){message(e.message,true)}}
function move(direction){sendCommand('move',{direction,duration_seconds:.5})}
async function refreshPreview(){if(!token()||!selected())return;try{let r=await fetch('/v1/devices/'+encodeURIComponent(selected())+'/preview',{headers:headers(),cache:'no-store'});if(!r.ok)throw Error();let url=URL.createObjectURL(await r.blob()),old=$('preview').src;$('preview').src=url;$('preview').hidden=false;$('placeholder').hidden=true;if(old.startsWith('blob:'))URL.revokeObjectURL(old)}catch(_){$('preview').hidden=true;$('placeholder').hidden=false}}
setInterval(()=>{if(token())refreshPreview()},700);setInterval(()=>{if(token())loadDevices().catch(()=>{})},3000);document.addEventListener('keydown',e=>{if(['INPUT','SELECT'].includes(document.activeElement.tagName))return;let d={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right'}[e.key];if(d){e.preventDefault();move(d)}if(e.key==='Escape')sendCommand('stop',{})});
if(token())loadDevices().catch(()=>showLogin());else showLogin();
</script></body></html>""".encode("utf-8")
